@prefix = http://localhost:1904/api

// resources
// All Books: /books
// One book:  /books/:id

### GET - Gets all books
# {
#     books: [
#         {
#             uri: /books/1,
#             title: "Book1"
#             author: "Author1" 
#         },
#         {
#             uri: /books/2,
#             title: "Book2"
#             author: "Author2" 
#         },

#     ]

# }


### Get All Books
GET {{prefix}}/books
Authorization: Bearer 7beaf3a4-6d2d-4e1f-90b6-2efb71552357

###
// GET - get a single book
GET {{prefix}}/books/2

###
// DELETE - deletes a book
DELETE {{prefix}}/books/1


### PUT - Updates a book
PUT {{prefix}}/books/2
Content-Type: application/json

{
    title: "NewBook",
    isbn: 23-298932480-32-34-2
}


// POST - Creates a new Book
POST {{prefix}}/books


# Resource   | GET    | PUT    | POST   | DELETE | 
# -----------|--------|--------|--------|--------|
# /books/    |   x    |        |   x    |        |
# -----------|--------|--------|--------|--------|
# /books/1   |   x    |   x    |        |   x    |








### Get the URI representation
GET 


PUT 


POST 

### Deletes the resource 
DELETE 


Create
Read
Update
Delete

